# Generated by Django 3.2.6 on 2021-08-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paying_guest.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of the Amenities you can provide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of the pg')),
                ('category', models.CharField(choices=[('men', 'Men'), ('ladies', 'ladies'), ('unisex', 'unisex')], max_length=6)),
                ('city', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Gurugoan', 'Gurugoan'), ('Hyderabad', 'Hyderabad'), ('Kolkata', 'Kolkata'), ('Kochi', 'Kochi'), ('Mangalore', 'Mangalore'), ('Mumbai', 'Mumbai'), ('Mysuru', 'Mysuru'), ('Noida', 'Noida'), ('Trivandrum', 'Trivandrum'), ('Vizag', 'Vizag')], max_length=19)),
                ('address', models.CharField(default=paying_guest.models.PayingGuest.default_address, max_length=250, verbose_name='Exact Address of PG')),
                ('daily_rent_charges_range', models.CharField(default='Rs 250 - Rs 450', max_length=100)),
                ('monthly_rental_charge', models.CharField(default='Rs 5000 - Rs 6000', max_length=100)),
                ('no_of_rooms_present', models.IntegerField(default=0)),
                ('no_of_beds_present', models.IntegerField(default=0)),
                ('amenities', models.ManyToManyField(related_name='amenities', to='paying_guest.Amenities')),
                ('comments', models.ManyToManyField(related_name='get_pg_comments', to='paying_guest.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PgRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_number', models.IntegerField(unique=True)),
                ('comments', models.ManyToManyField(related_name='get_room_comments', to='paying_guest.Comment')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paying_guest.payingguest', verbose_name='Which PG this room belongs to')),
            ],
            options={
                'verbose_name_plural': 'PgRooms',
                'unique_together': {('pg', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='PgImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=paying_guest.models.PgImage.get_upload_filename)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pgimages', to='paying_guest.payingguest')),
            ],
            options={
                'verbose_name_plural': 'PgImages',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_comments', to='paying_guest.payingguest'),
        ),
        migrations.AddField(
            model_name='comment',
            name='pgroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_room_comments', to='paying_guest.pgroom'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PgCot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cot_number', models.IntegerField()),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paying_guest.payingguest', verbose_name='Which PG this cot belongs to')),
                ('pg_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paying_guest.pgroom', verbose_name='Which PG this cot belongs to')),
            ],
            options={
                'verbose_name_plural': 'PgCots',
                'unique_together': {('pg', 'cot_number', 'pg_room')},
            },
        ),
    ]
