# Generated by Django 3.2.6 on 2021-08-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paying_guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payingguest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='pgroom',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
