# Generated by Django 3.2.6 on 2021-08-15 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paying_guest', '0002_auto_20210815_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_comments', to='paying_guest.payingguest')),
                ('pgroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pg_room_comments', to='paying_guest.pgroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
