# Generated by Django 3.2.6 on 2021-08-15 18:07

from django.db import migrations, models
import paying_guest.models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_guest', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payingguest',
            name='pg_phone_no',
            field=models.CharField(default='0000000000', max_length=10, unique=True, validators=[paying_guest.models.PayingGuest.validate_phone_numbers]),
        ),
    ]
