# Generated by Django 3.2.6 on 2021-08-15 18:08

from django.db import migrations, models
import paying_guest.models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_guest', '0004_payingguest_pg_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payingguest',
            name='pg_phone_no',
            field=models.CharField(max_length=10, unique=True, validators=[paying_guest.models.PayingGuest.validate_phone_numbers]),
        ),
    ]
