# Generated by Django 3.2.6 on 2021-08-15 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paying_guest', '0005_alter_payingguest_pg_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgroom',
            name='occupied_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_occupied_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
