# Generated by Django 3.2.6 on 2021-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paying_guest', '0007_auto_20210815_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='pgcot',
            name='daily_rent',
            field=models.IntegerField(default=250),
        ),
        migrations.AddField(
            model_name='pgcot',
            name='is_rent_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pgcot',
            name='monthly_rent',
            field=models.IntegerField(default=5500),
        ),
    ]
