# Generated by Django 3.2.6 on 2021-08-15 18:14

from django.db import migrations, models
import django.db.models.deletion
import user_accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_alter_userprofiles_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.FileField(upload_to=user_accounts.models.UserFiles.get_filename_aadhar)),
                ('pan', models.FileField(upload_to=user_accounts.models.UserFiles.get_filename_pan)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_files', to='user_accounts.userprofiles')),
            ],
        ),
    ]
