# Generated by Django 3.2.6 on 2021-08-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0004_alter_userfiles_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfiles',
            options={'verbose_name_plural': 'UserFiles'},
        ),
    ]
